name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"] # ⚠️ S'assurer que le CI passe avant
    branches: [main, develop]
    types:
      - completed

jobs:
  deploy:
    name: 🚀 Deploy to Vercel
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # ✅ CD ne se fait que si CI a réussi
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
