name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  setup:
    name: 📥 Setup & Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Save Dependencies
        run: cp -r node_modules /tmp/node_modules

  lint:
    name: 🎨 Lint & Format
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Dependencies
        run: cp -r /tmp/node_modules node_modules

      - name: Run Prettier (Check format)
        run: npm run format -- --check

      - name: Run ESLint
        run: npm run lint

  build:
    name: 🏗️ Build Project
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Dependencies
        run: cp -r /tmp/node_modules node_modules

      - name: Build the project
        run: npm run build

  test:
    name: ✅ Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Dependencies
        run: cp -r /tmp/node_modules node_modules

      - name: Run Tests
        run: npm test
